### ISSUE TITLE
提交翻译

### ISSUE THREAD

**Issue by book8899174** [ShinyGroup/ShinyColors#6]
汉化了一下新活动的序章

**Comment by book8899174** [comment]
シャニマスのサマー・ミーツ・ワンダーランドイベントのオープニングの中国語翻訳したファイルです。
[game_event_communications_400101501.zip](https://github.com/ShinyGroup/ShinyColors/files/3452939/game_event_communications_400101501.zip)

**Comment by lzgzhyf** [comment]
如果希望贡献翻译的话，欢迎加入我们的群组1018154722，里面有工作流程，翻译规范以及进度安排表
